<h1>History</h1>
<img src="/img/static-content-divider.gif" alt="" style="margin:5px 0px">
<img style="float:right;" alt="" src="/img/static/history2.jpg">
<p class="headline">Michel Herbelin is an independent, deliberately small-scale French company that follows in the purest tradition of watchmaking.  Their exclusive collection reflects the times in which we live with a very definite "art de vivre".  Each creation has its own personal style and is finished to the highest possible standards.</p>
<p>The Michel Herbelin story began in 1947 in Charquemont, France in the heart of the Jura mountains - the home of watchmaking since the 18th century.  Michel Herbelin was a passionate believer in traditional fine watchmaking and decided to make a stand against the new mass production techniques that were looming on the horizon and threatening to oust the old techniques.</p>
<p>In 1947, Michel Herbelin set up his own company with the avowed intention of making watches of the highest quality, to the same standards as the great names of the day.  Herbelin worked in close collaboration with his suppliers and with the specialist laboratories in the region to come up with elegant, technically sophisticated creations that provided the basis for his burgeoning reputation.  With the appearance of the company's logo in 1965, the Herbelin name became a well-known brand.</p>
<p>In 1972, Michel’s son, Jean-Claude Herbelin joined the company.  The advent of quartz technology provided a boost for Michel’s creative instincts resulting in innovations noted by the watch industry such as extra slim watches and the wire bangle watches for which the brand became synonymous.  When Jean-Claude took over as head of the company upon his father’s retirement, he steered the brand into a new phase, developing a brand image based on creativity and attention to detail through worldwide communication campaigns.</p>
<p>Today, the company is still run by Jean-Claude Herbelin and his brother Pierre-Michel.  Now with a third generation of Herbelin family members involved in the company, Michel Herbelin is truly one of the only Independent watch manufacturers of note in existence.  Michel Herbelin is an international brand and produces over 150,000 watches per year which are exported to over 50 countries worldwide.   The brand is positioned in the middle of the market with the majority of the collection retailing from £250-£1000.  In France, the brand is market leader in the mid market segment. In the UK and Republic of Ireland, Michel Herbelin is stocked by a strong network of over 350 leading quality jewellers.</p>
<p>Designed and made in France, all watches have Swiss movements.  The brand therefore benefits from the flair of French design with the precision of Swiss engineering - hence the company's advertising tag line: Swiss Heart, French Soul.</p>
<p>The collection is split into three main categories:  Sport, Classic and Boutique watches.  Within each category, there are distinctive "families".  The flagship collection, which can be found within the Sport category is NEWPORT.  Inspired by the sea, the collection takes its name from the America’s cup and the race to Newport Rhode Island.  All Newport watches are water resistant to at least 5 Atmospheres and are fitted with a scratch-resistant sapphire crystal.</p>
<p>The Classic collection is the epitome of French style and good design.  The main family groups are KHARGA - distinctive with their rectangular cases and elegant lines and AMBASSADOR – stylish yet understated.</p>
<p>The Boutique collection consists of a variety of stylish models that can literally be worn as a piece of jewellery that tells the time.  Ranging from elegant bangle watches, to delicate bracelet versions and colourful strap models there is a watch to suit every taste and wrist.  The main family groups within the Boutique collection are ANTARES, LUNA and SALAMBO.</p>